server:
  port: 8083

spring:
  r2dbc:
    url: r2dbc:pool:postgres://localhost:5432/webfluxsecuritydb
    username: postgres
    password: postgres
  flyway:
   url: jdbc:postgresql://localhost:5432/webfluxsecuritydb
   user: postgres
   password: postgres
   schemas: db
   locations: classpath:db/migration


jwt:
  password:
    encoder:
      secret: FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEVBX43g
      iteration: 64
      keyLength: 256
  secret: b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e
